### ISSUE TITLE
Github router only working for unsafe URLs?

### ISSUE THREAD

**Issue by urkle** [sensiblecodeio/hookbot#49]
Why does the github router only work for unsafe URLs?  I can put a url w/ a token in the github webhook and receive all the messages fine there, but the github router ignores them.

**Comment by pwaller** [comment]
It may just be unimplemented, I don't see a reason not to implement it except that we verify that messages came from github using github's secret and the signature method, so tokens might not be needed if you're using that.

It could also be that when I implemented this a year and a half ago that I couldn't get what you described working.

A patch to implement it would be welcomed :)

**Comment by pwaller** [comment]
I'm going to close this for now since there is a reasonable workaround. If you signal an intent to implement this and would like me to reopen it please just say and I'll reopen.

**Comment by urkle** [comment]
I would like to implement this, as I'd rather not use unsafe mode at all :)

I'll open a PR with changes (I have a few other PRs I'll be opening as well to fix other issues)
