### ISSUE TITLE
No documentation for https/wss connection

### ISSUE THREAD

**Issue by Gabibaskes** [sensiblecodeio/hookbot#53]
I couldn't find anywhere the way to set the certificates to be able to perform https/wss connections and I suspect that's the reason why i can't use these protocols.

**Comment by pwaller** [comment]
Indeed there is not a way to configure. It is assumed that HTTPS is configured through some sort of proxy such as https://github.com/sensiblecodeio/tiny-ssl-reverse-proxy, nginx or a load balancer.

We don't have plans to implement this directly in hookbot. We may entertain a pull request but no promises.
